# Generated by Django 3.1.3 on 2021-01-29 12:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='default_zycnhz.jpg', upload_to='avatars'),
        ),
    ]
