# Generated by Django 3.1.3 on 2021-01-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thumbnail',
        ),
    ]
