# Generated by Django 3.1.3 on 2021-01-30 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=255, unique=True)),
                ('barangay', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('longitude', models.FloatField(max_length=255)),
                ('latitude', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthplace', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=255)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='profiles')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.person')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('previous', models.FloatField(max_length=255)),
                ('acquired', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.address')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.person')),
            ],
        ),
    ]
