# Generated by Django 3.1.3 on 2021-01-31 03:18

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profiles'),
        ),
    ]
